name: sound_studio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_login.png
    - assets/google_login_small.png
    - assets/kakao_login_medium_wide.png
    - assets/naver_login.png
    - assets/google_login_icon.png
    - assets/naver_login_icon.png
    - assets/kakao_login_icon.png